package com.example.superapp.models

data class Super(val id : Int,
                 val name: String,
                 val description: String,
                 val image : String,
                 val publisherId : Int
){
    companion object {
        val supers = mutableListOf<Super>(
            // Marvel
            Super(1, "Spider-Man",  "Un joven estudiante, Peter Parker, que tras ser mordido por una araña radioactiva obtiene habilidades arácnidas como fuerza sobrehumana, trepar paredes y sentido arácnido. Lucha para proteger a Nueva York mientras equilibra su vida personal y su responsabilidad como héroe.", "https://i.pinimg.com/originals/d3/a4/98/d3a498e87019df9a74cb21902628d630.png",  1),
            Super(2, "Iron Man",  "Tony Stark, un genio inventor y multimillonario, crea una armadura avanzada para escapar de su cautiverio. Como Iron Man, usa su traje equipado con tecnología de última generación para combatir amenazas globales mientras dirige Industrias Stark.", "https://i.pinimg.com/originals/79/02/75/7902754f733eceeb7fe52df419161ad6.png",  1),
            Super(3, "Captain America", "Steve Rogers es un supersoldado que, tras ser inyectado con el suero del supersoldado durante la Segunda Guerra Mundial, lucha por la libertad y la justicia. Porta su escudo de vibranio y es el líder moral de los Vengadores.", "https://i.pinimg.com/originals/02/3b/91/023b91cf122b096931e0299e4a6af2fb.png",  1),
            Super(4, "Thor",  "El dios del trueno, hijo de Odín, rey de Asgard. Thor es un guerrero inmortal que empuña el martillo Mjolnir, capaz de controlar el trueno y volar. Defiende la Tierra de amenazas cósmicas y protege los Nueve Reinos.", "https://i.pinimg.com/originals/69/04/4e/69044ede53faf040d83eba25abb2a800.png",  1),
            Super(5, "Hulk",  "El Dr. Bruce Banner se transforma en Hulk, un ser de fuerza imparable, tras exponerse a radiación gamma. Aunque su alter ego es destructivo e incontrolable, Banner lucha por controlar al monstruo dentro de él para usar su poder en defensa de la humanidad.", "https://i.pinimg.com/originals/9d/28/ed/9d28ed4f08d480d51708e1213b8a94a2.png",  1),
            Super(6, "Black Widow",  "Natasha Romanoff es una agente entrenada en las artes del espionaje, combate cuerpo a cuerpo y operaciones encubiertas. Antiguamente una espía de la KGB, ahora es miembro de los Vengadores y utiliza sus habilidades para luchar contra el mal global.", "https://i.pinimg.com/originals/95/95/c2/9595c24319c3e1cf65082f4aaf56c47d.png",  1),
            Super(7, "Hawkeye",  "Clint Barton, conocido como Hawkeye, es el arquero más preciso del mundo. Utiliza su extraordinaria puntería y un arco especial con flechas variadas para enfrentarse a enemigos poderosos. A pesar de no tener superpoderes, es uno de los Vengadores más valientes.", "https://i.pinimg.com/originals/4b/c5/cc/4bc5ccd0e2bf4b52e0a8468850b3053b.png",  1),
            Super(8, "Scarlet Witch", "Wanda Maximoff posee habilidades de manipulación de la realidad, telequinesis y energía mágica. Tras perder a su hermano, se une a los Vengadores, pero su poder descontrolado la lleva a enfrentarse a dilemas emocionales y a convertirse en una de las más poderosas del equipo.", "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/820ad535-c310-4704-a9bc-eecf26bba444/da0m5v2-fd3da212-97e5-498b-8c00-61ca7545c75f.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzgyMGFkNTM1LWMzMTAtNDcwNC1hOWJjLWVlY2YyNmJiYTQ0NFwvZGEwbTV2Mi1mZDNkYTIxMi05N2U1LTQ5OGItOGMwMC02MWNhNzU0NWM3NWYucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.5njncVniLJdKsC3U3PdUqkQcMTnosAxAA8acMQW3p_s",  1),
            Super(9, "Doctor Strange",  "Stephen Strange, un ex cirujano de renombre, aprende las artes místicas tras un accidente que arruina su carrera médica. Como Hechicero Supremo, defiende la Tierra de amenazas mágicas y extradimensionales, utilizando artefactos como el Ojo de Agamotto.", "https://static.wikia.nocookie.net/death-battle-en-espanol/images/8/87/MarvelDoctorStrange.png/revision/latest?cb=20220523045217&path-prefix=es",  1),
            Super(10, "Black Panther",  "T'Challa, el rey de Wakanda, toma el manto de Black Panther tras la muerte de su padre. Con habilidades mejoradas gracias a la hierba corazón y un traje de vibranio avanzado, protege su nación tecnológicamente avanzada y lucha por el bienestar global.", "https://i.pinimg.com/originals/85/3c/99/853c999363fa3170fdb5ecd6b0f1e229.png",  1),

            //DC comics
            Super(11, "Superman", "El último hijo de Krypton, Superman es conocido por sus increíbles poderes como fuerza sobrehumana, visión de calor, vuelo y resistencia. Criado en la Tierra como Clark Kent, se convierte en el protector de Metrópolis y un símbolo de esperanza.", "https://i.pinimg.com/originals/ce/71/d8/ce71d8bd7654e167591080f1ca63fc83.png",  2),
            Super(12, "Batman", "Bruce Wayne es un multimillonario que, tras presenciar el asesinato de sus padres, decide luchar contra el crimen en Gotham como Batman. Sin poderes sobrehumanos, usa su inteligencia, habilidades de combate y tecnología avanzada para enfrentar a sus enemigos.", "https://i.pinimg.com/originals/d5/87/77/d5877773508cef948af997e040a99870.png",  2),
            Super(13, "Wonder Woman", "Diana de Themyscira, hija de Zeus, es una guerrera amazona inmortal con habilidades sobrehumanas. Con su lazo de la verdad, brazaletes indestructibles y un fuerte sentido de justicia, lucha por la paz y la igualdad en el mundo.", "https://i0.wp.com/www.vectorizando.com/wp-content/uploads/wonder-woman-cartoon-6e09dd0f.png?fit=500%2C500&ssl=1",  2),
            Super(14, "The Flash", "Barry Allen es un científico forense que adquiere la capacidad de correr a velocidades extremas tras ser alcanzado por un rayo. Como The Flash, protege Central City usando su velocidad para manipular el tiempo y combatir el crimen.", "https://i.pinimg.com/originals/83/10/59/83105916580f7b38172a68bc0cd688bb.png",  2),
            Super(15, "Aquaman", "Arthur Curry, mitad humano y mitad atlante, es el rey de la Atlántida. Con habilidades como el control del agua, la comunicación con las criaturas marinas y una fuerza sobrehumana, defiende tanto los océanos como la superficie.", "https://static.wikia.nocookie.net/death-battle-en-espanol/images/0/0b/Aquaman_Super_Friends.png/revision/latest?cb=20221003154805&path-prefix=es",  2),
            Super(16, "Green Lantern", "Hal Jordan es un miembro de los Green Lantern Corps, una fuerza de guardianes intergalácticos. Usando un anillo de poder que manifiesta construcciones de energía verde, protege la Tierra y otros sectores del universo.", "https://www.pngall.com/wp-content/uploads/10/Green-Lantern-PNG-Images-HD.png",  2),
            Super(17, "Cyborg", "Victor Stone es un ser mitad hombre y mitad máquina, mejorado con tecnología cibernética avanzada. Como Cyborg, tiene acceso a sistemas informáticos, armamento y superpoderes mecánicos que usa para luchar contra amenazas tecnológicas y alienígenas.", "https://static.wikia.nocookie.net/cartoonnetwork/images/a/a3/Cyborg.png/revision/latest?cb=20191027230310&path-prefix=es",  2),
            Super(18, "Shazam", "Billy Batson es un adolescente que, al pronunciar la palabra 'Shazam', se transforma en un superhéroe adulto con poderes divinos, como fuerza, velocidad y el control de rayos. Lucha contra el mal con una mentalidad joven y aventurera.", "https://static.wikia.nocookie.net/death-battle-en-espanol/images/c/c7/Shazam.png/revision/latest?cb=20190320181621&path-prefix=es",  2),
            Super(19, "Green Arrow", "Oliver Queen es un multimillonario que, tras naufragar en una isla desierta, desarrolla habilidades excepcionales con el arco. Como Green Arrow, usa sus dotes de combate y su arco para combatir el crimen en Star City.", "https://i.pinimg.com/originals/e4/08/ba/e408bacd4e65e8973a7b7b76f904004d.png",  2),
            Super(20, "Martian Manhunter", "J'onn J'onzz es un marciano que posee una variedad de poderes, incluyendo la telepatía, el vuelo, la invisibilidad y la capacidad de cambiar de forma. Como uno de los últimos de su especie, lucha por la justicia en la Tierra.", "https://static.wikia.nocookie.net/all-worlds-alliance/images/8/84/4696826030f121f0d836650a965c57c7.png/revision/latest?cb=20190304060411",  2)

        )
    }
}
